### ISSUE TITLE
[IMPROVEMENT] Implement Estimator and Experiment APIs

### ISSUE THREAD

**Issue by kidtronnix** [Atomu2014/pnn-demo#4]
Hi,

So first off big thanks to this amazing project. I got your code running on my own data and saw some amazing results, specifically with `pnn2`.

I am now trying to productionize this model and want to implement `pnn2` in the Estimator and Experiment so it can easily be run on ML Engine, produce tensorboard friendly eval metrics, and so the model can be saved and be run by existing prediction serving tools.

I would really appreciate if anybody could help port this codebase to a format similar to this...

[https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/census/customestimator](https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/census/customestimator)

**Comment by Atomu2014** [comment]
Thanks for your attention! You are welcomed to contact me at kevinqu@apex.sjtu.edu.cn.

From the code perspective, I am glad that my code works well for your task. But I do not know what should I do to port this code since I am not familiar with GCP.

From the research perspective, I think we can have a further discussion on this project. Recently I submitted a journal version of this work to ``ACM Transactions on Information Systems`` with a lot of new proposals and experiments beyond this code. The journal version is currently under review and due to some reason, I can not publish this version on arxiv. But we can discuss it privately.
