### ISSUE TITLE
你的readme里面公式都没有显示好啊

### ISSUE THREAD

**Issue by murdonson** [Atomu2014/pnn-demo#9]
如题 请修复一下

**Comment by Atomu2014** [comment]
Thanks for your attention and sorry for the late response. These days my email service got some problem...
I know the problem you've mentioned, that is because auto-rendering is banned by github...
I have browsed some solutions, and found no elegant solutions except for inserting images...
Since the formulas are easy to read, I just leave as it.
Or you can use any markdown software to render the readme file.
